local s = require('network_settings')

os.execute("git ls-files | zip project.zip -@")
os.execute("scp project.zip root@"..s.server_ip..":/root/")
os.execute("rm project.zip")
os.execute("ssh root@"..s.server_ip)
os.execute("rm -rf game")
os.execute("unzip project.zip -d game")
os.execute("rm project.zip")
os.execute("exit")